#pragma once

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 8000

#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
//#define RETRO_TAPPING

#define UNICODE_SELECTED_MODES UC_LNX, UC_WINC, UC_WIN
